In [21]:
import os; os.chdir('..')

In [2]:
from Utils.html_tag_extractor import html_tag_extractor

In [3]:
# html_tag_extractor.print_html_raw('https://www.igeeksblog.com/best-cat-ear-headphones/')


In [4]:
html_tag_extractor.extract_html_template('https://www.igeeksblog.com/best-cat-ear-headphones/')

'<[document]><html><head><title>text</title></head><body><div></div><div><div><nav><div><a><img></a><a><img></a></div><span><i></i></span></nav></div><aside><div><div><div><ul><li><a>text</a><ul><li><a>text</a></li></ul></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li></ul></div></div><div><div><p>text</p><a><img></a></div></div><div><div><ul><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li></ul></div></div><div><div><p>text</p><iframe></iframe></div></div><div><div><div><div><a><i></i></a></div><div><a><i></i></a></div><div><a><i></i></a></div><div><a><i></i></a></div><div><a><i></i></a></div><div><a><img></a></div></div></div></div><div><div><a><img></a><br>text</div></div></div></aside></div><div><div><header><div><div><div><span><i></i></span><div><a><img></a><a><img></a></div><

In [5]:
url= "https://python.langchain.com/docs/integrations/chat/anthropic"

html_tag_extractor.extract_html_template(url)

'<[document]><html><head><title>text</title></head><body><div><div><a>text</a></div><nav><div><div><button><svg><path></path></svg></button><a><b>text</b></a><a>text</a><a>text</a><a>text</a><a>text<svg><path></path></svg></a></div><div><a>text</a><a>text</a><a></a><div><button><svg><path></path></svg><svg><path></path></svg></button></div><div><div><button><div><svg><path></path><path></path></svg><input></div><div><span>text</span><span>text</span></div></button><div></div></div></div></div></div><div></div></nav><div><button></button><div><aside><div><div><nav><ul><li><div><a>text</a></div><ul><li><div><a>text</a><button></button></div></li><li><div><a>text</a><button></button></div><ul><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li><li><a>text</a></li></ul></li><li><div><a

In [5]:
from Utils.client import generate_top_urls

In [6]:
list_of_urls= generate_top_urls("Spotify free vs premium", 10)
list_of_urls

['https://www.tomsguide.com/face-off/spotify-free-vs-premium',
 'https://www.soundguys.com/free-spotify-vs-spotify-premium-36632/',
 'https://www.headphonesty.com/2021/08/spotify-free-vs-premium/',
 'https://history-computer.com/spotify-free-vs-premium-comparison-whats-the-difference/',
 'https://www.cnet.com/tech/services-and-software/good-reasons-to-pay-for-spotify/',
 'https://support.spotify.com/us/article/premium-plans/',
 'https://www.geeky-gadgets.com/whats-difference-between-spotify-free-and-premium/',
 'https://blog.tunemymusic.com/spotify-free-vs-premium-a-full-comparison/',
 'https://www.howtogeek.com/350288/spotify-free-vs-premium-is-it-worth-upgrading/',
 'https://www.makeuseof.com/spotify-free-vs-spotify-premium-main-differences/']

In [30]:
# idx= [0, 3, 4]

In [41]:
# html_templates= ''


# for i in idx:
#     template= html_tag_extractor.extract_html_template(list_of_urls[i])
#     if template:
#         print(template)
#         print(list_of_urls[i])
#         print()
#         html_templates+=template+'\n'
        
#         with open(f'dummy_files/template-{i}.html', 'w') as f:
#             f.write(list_of_urls[i]+template)
#         i+=1


<[document]><html><head><title>text</title></head><body><div><div><a>text</a><div><div><div><div><a><svg><title>text</title><desc>text</desc><path></path></svg></a><a><span>text</span></a></div></div><div><nav><ul><li><a><span>text</span><svg><title>text</title><desc>text</desc><path></path></svg></a><span>text</span></li><li><a>text</a><span>text</span></li><li><a>text</a><span>text</span></li><li><a>text</a><span>text</span></li><li><a>text</a><span>text</span></li><li><button><span>text</span><span>text</span><svg><title>text</title><path></path></svg></button></li></ul></nav></div></div><div><div><a><svg><title>text</title><desc>text</desc><path></path></svg></a><div><button><span>text</span><svg><title>text</title><path></path></svg></button></div></div></div></div><div><div></div><div></div><main><article><div><div><div><div><ul><li><a>text</a></li></ul><div><h1>text</h1></div><h2>text</h2></div><div><div><p><span>text</span><span><span></span><span><a>text</a></span><span>text<s

In [8]:
list_of_urls.remove('https://support.spotify.com/us/article/premium-plans/')
list_of_urls

['https://www.tomsguide.com/face-off/spotify-free-vs-premium',
 'https://www.soundguys.com/free-spotify-vs-spotify-premium-36632/',
 'https://www.headphonesty.com/2021/08/spotify-free-vs-premium/',
 'https://history-computer.com/spotify-free-vs-premium-comparison-whats-the-difference/',
 'https://www.cnet.com/tech/services-and-software/good-reasons-to-pay-for-spotify/',
 'https://www.geeky-gadgets.com/whats-difference-between-spotify-free-and-premium/',
 'https://blog.tunemymusic.com/spotify-free-vs-premium-a-full-comparison/',
 'https://www.howtogeek.com/350288/spotify-free-vs-premium-is-it-worth-upgrading/',
 'https://www.makeuseof.com/spotify-free-vs-spotify-premium-main-differences/']

In [15]:
html_templates= ''
i= 100
for url in list_of_urls[:8]:
    template= html_tag_extractor.extract_html_template(url)
    if template:
        print(template)
        print(url)
        print()
        html_templates+=template+'\n'
        with open(f'dummy_files/template-{i}.html', 'w') as f:
            f.write(url+template)
        i+=1
    
    

<[document]><html><head>text<title>text</title>texttexttexttexttexttexttexttexttexttext</head><body>text<a>text</a>text<nav><input><input><div><div><label><span>text</span></label><label><span>text</span></label><div><a><span><svg><title>text</title><g><g><g><g><path></path><path></path><path></path><path></path><path></path><path></path><path></path><polygon></polygon><path></path><path></path></g></g></g></g></svg></span><span>text</span><span></span></a></div><input><label><span>text</span><span><svg><path></path></svg></span></label><form><label>text</label><input><button><span><svg><path></path></svg></span></button></form><div><div>text<span><svg><path></path></svg></span></div></div><div><a><abbr>text</abbr></a></div><div><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><path></path>

In [10]:
from main import generate_intent_v2

generate_intent_v2("spotify free vs premium")

Spotify Free vs. Premium: Should you pay to play? www.tomsguide.com https://www.tomsguide.com/face-off/spotify-free-vs-premium Arguably the biggest difference between Spotify's Free and Premium tiers is the latter's complete lack of ads. That goes for both the visual ads ... Spotify Free vs Premium: Is it worth it? www.soundguys.com https://www.soundguys.com/free-spotify-vs-spotify-premium-36632/ First, there is the Spotify Premium Individual subscription, which is $9.99/month. This allows access to all the Premium features such as no ad interruptions, ... Spotify Free vs. Premium Comparison: What's the Difference? history-computer.com https://history-computer.com/spotify-free-vs-premium-comparison-whats-the-difference/ Spotify Free is completely free, while Premium costs $9.99 per month. There are also three other plans: $15.99/month for a family plan (up to ... Spotify Premium vs. Free: 6 Good Reasons to Pay www.cnet.com https://www.cnet.com/tech/services-and-software/good-reasons-to

('navigational',
 0.8656492233276367,
 tensor([[0.8628],
         [0.8656],
         [0.8425],
         [0.8482],
         [0.8333]]))

In [16]:
print(html_templates)

<[document]><html><head>text<title>text</title>texttexttexttexttexttexttexttexttexttext</head><body>text<a>text</a>text<nav><input><input><div><div><label><span>text</span></label><label><span>text</span></label><div><a><span><svg><title>text</title><g><g><g><g><path></path><path></path><path></path><path></path><path></path><path></path><path></path><polygon></polygon><path></path><path></path></g></g></g></g></svg></span><span>text</span><span></span></a></div><input><label><span>text</span><span><svg><path></path></svg></span></label><form><label>text</label><input><button><span><svg><path></path></svg></span></button></form><div><div>text<span><svg><path></path></svg></span></div></div><div><a><abbr>text</abbr></a></div><div><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><path></path>

In [19]:
import openai
def generate_object_description(text, print_lists=False):

    openai.api_base = "https://openrouter.ai/api/v1"
    # openai.api_key = "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"
    openai.api_key = "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"



    response = openai.ChatCompletion.create(
            # model="anthropic/claude-2", # Optional (user controls the default)
            # model="meta-llama/codellama-34b-instruct", # Optional (user controls the default)
            model="openai/gpt-4-32k", # Optional (user controls the default)
            # model="meta-llama/llama-2-70b-chat", # Optional (user controls the default)
            messages=[
                        {"role": "user", "content": f"create a html template using structure from all of the following html templates and deduping the redundant ones:  \n{text}?"},
                    ],
                # headers={ "HTTP-Referer": $YOUR_SITE_URL, # To identify your app
                #         "X-Title": $YOUR_APP_NAME },
                headers={ "HTTP-Referer": "https://openrouter.ai/api/v1", # To identify your app
                        "X-Title": "Deepankar" },
            )
    reply = response.choices[0].message.content
    # l= reply.content.split('\n')
    # svo_triplets= []
    # for triplet in l:
    #     triplet= triplet.replace("'", '') 
    #     triplet= triplet.replace('"', '') 
    #     triplet= triplet.replace('(', '') 
    #     triplet= triplet.replace('[', '') 
    #     triplet= triplet.replace(']', '') 
    #     triplet= triplet.replace(')', '') 
    #     triplet= triplet.strip() 
    #     triplet= triplet.split(', ') 
    #     triplet[-1]= triplet[-1].replace(',', '') 
    #     svo_triplets.append(tuple(triplet))
    
    if print_lists:
        print(reply)
    
    return reply
    
    
    
    

In [51]:
l= ['https://facebook.com', 'https://ig.com']

In [53]:
html_templates= '''
'''
m= 1
for i in l:
    template= html_tag_extractor.extract_html_template(i)
    with open(f'{m}.html', 'w') as f:
        f.write(template)
    html_templates+=template+'\n'
    m+=1

In [12]:
html_templates

'<[document]><html><head>text<title>text</title>texttexttexttexttexttexttexttexttexttext</head><body>text<a>text</a>text<nav><input><input><div><div><label><span>text</span></label><label><span>text</span></label><div><a><span><svg><title>text</title><g><g><g><g><path></path><path></path><path></path><path></path><path></path><path></path><path></path><polygon></polygon><path></path><path></path></g></g></g></g></svg></span><span>text</span><span></span></a></div><input><label><span>text</span><span><svg><path></path></svg></span></label><form><label>text</label><input><button><span><svg><path></path></svg></span></button></form><div><div>text<span><svg><path></path></svg></span></div></div><div><a><abbr>text</abbr></a></div><div><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><circle></circle><path></path></svg></a><a><svg><path></path

In [20]:
x= generate_object_description(html_templates)
x

APIError: Prompt tokens limit exceeded: 29898 > 20746. To increase: visit https://openrouter.ai/account and add more credits {"error":{"message":"Prompt tokens limit exceeded: 29898 > 20746. To increase: visit https://openrouter.ai/account and add more credits","code":402}} 402 {'error': {'message': 'Prompt tokens limit exceeded: 29898 > 20746. To increase: visit https://openrouter.ai/account and add more credits', 'code': 402}} {'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Authorization, X-Api-Key, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, HTTP-Referer, X-Windowai-Title, X-Openrouter-Title, X-Title, X-Stainless-Lang, X-Stainless-Package-Version, X-Stainless-OS, X-Stainless-Arch, X-Stainless-Runtime, X-Stainless-Runtime-Version', 'Access-Control-Allow-Methods': 'GET,OPTIONS,PATCH,DELETE,POST,PUT', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'public, max-age=0, must-revalidate', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Date': 'Thu, 07 Sep 2023 05:33:48 GMT', 'Server': 'Vercel', 'Strict-Transport-Security': 'max-age=63072000', 'X-Matched-Path': '/api/v1/chat/completions', 'X-Vercel-Cache': 'MISS', 'X-Vercel-Id': 'iad1::tkwmf-1694064825308-3d5c299c2b52', 'Transfer-Encoding': 'chunked'}

In [ ]:
with open('dummy_files/output.html', 'w') as f:
    f.write(x.replace("\n", ''))

In [17]:
# x

'\n```\n\n### 2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2'

In [57]:
import requests
from bs4 import BeautifulSoup

In [58]:
url= 'https://openrouter.ai/docs#models'

In [59]:
response = requests.get(url)


In [60]:
soup = BeautifulSoup(response.text, 'html.parser')

In [61]:
soup.tagStack

[<!DOCTYPE html>
 <html lang="en"><head><meta charset="utf-8"/><meta content="width=device-width" name="viewport"/><title>OpenRouter</title><meta content="follow, index" name="robots"/><link href="/favicon.ico" rel="shortcut icon"/><meta content="Authenticate and use your AI models in one place" name="description"/><meta content="https://openrouter.ai/docs" property="og:url"/><meta content="website" property="og:type"/><meta content="OpenRouter" property="og:site_name"/><meta content="Authenticate and use your AI models in one place" property="og:description"/><meta content="OpenRouter" property="og:title"/><meta content="https://openrouter.ai/og.png" property="og:image"/><meta content="summary_large_image" name="twitter:card"/><meta content="@openrouterai" name="twitter:site"/><meta content="OpenRouter" name="twitter:title"/><meta content="Authenticate and use your AI models in one place" name="twitter:description"/><meta content="https://openrouter.ai/og.png" name="twitter:image"/><m

In [22]:
from main import generate_intent_v2

In [24]:
from Utils.client import generate_top_urls

In [69]:
generate_top_urls("spotify free vs premium")

['https://www.tomsguide.com/face-off/spotify-free-vs-premium',
 'https://www.soundguys.com/free-spotify-vs-spotify-premium-36632/',
 'https://www.headphonesty.com/2021/08/spotify-free-vs-premium/',
 'https://www.quora.com/What-is-the-difference-between-free-Spotify-and-Premium',
 'https://history-computer.com/spotify-free-vs-premium-comparison-whats-the-difference/',
 'https://www.cnet.com/tech/services-and-software/good-reasons-to-pay-for-spotify/',
 'https://support.spotify.com/us/article/premium-plans/',
 'https://www.geeky-gadgets.com/whats-difference-between-spotify-free-and-premium/',
 'https://www.spotify.com/us/premium/',
 'https://www.viwizard.com/spotify-music-tips/spotify-free-vs-premium.html']

In [72]:
generate_intent_v2("spotify free vs premium")

Spotify Free vs. Premium: Should you pay to play? www.tomsguide.com https://www.tomsguide.com/face-off/spotify-free-vs-premium Arguably the biggest difference between Spotify's Free and Premium tiers is the latter's complete lack of ads. That goes for both the visual ads ... Spotify Free vs Premium: Is it worth it? www.soundguys.com https://www.soundguys.com/free-spotify-vs-spotify-premium-36632/ First, there is the Spotify Premium Individual subscription, which is $9.99/month. This allows access to all the Premium features such as no ad interruptions, ... Spotify Free vs. Premium Comparison: What's the Difference? history-computer.com https://history-computer.com/spotify-free-vs-premium-comparison-whats-the-difference/ Spotify Free is completely free, while Premium costs $9.99 per month. There are also three other plans: $15.99/month for a family plan (up to ... What is the difference between free Spotify and Premium? www.quora.com https://www.quora.com/What-is-the-difference-between-

('navigational',
 0.8687077164649963,
 tensor([[0.8669],
         [0.8687],
         [0.8446],
         [0.8523],
         [0.8388]]))

In [26]:
from main import generate_base_embeddings_v2

In [73]:
s= "cats fight with dogs"
sl= s.split(' ')
sl

['cats', 'fight', 'with', 'dogs']

In [74]:
import numpy as np

In [75]:
e2= np.mean(generate_base_embeddings_v2(sl), axis=0)

In [76]:
s= "car runs faster than bike"
sl= s.split(' ')
sl
e1= np.mean(generate_base_embeddings_v2(sl), axis=0)


In [77]:
e1==e2

array([False, False, False, ..., False, False, False])

In [78]:
from main import generate_cosine_similarity

In [79]:
generate_cosine_similarity(e1, e2)

tensor([[0.9320]])

: 