In [1]:
import os; os.chdir('..')

In [2]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

2023-10-04 10:26:02.857823: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-04 10:26:04.194724: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
bert_model_name = 'small_bert/bert_en_uncased_L-8_H-512_A-8' 
# bert_model_name = 'bert_en_cased_L-12_H-768_A-12' 

map_name_to_handle = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/3',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/3',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-2_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-2_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-2_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-768_A-12/1',
    'small_bert/bert_en_uncased_L-4_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-4_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-4_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-4_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-768_A-12/1',
    'small_bert/bert_en_uncased_L-6_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-6_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-6_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-6_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-6_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-6_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-6_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-6_H-768_A-12/1',
    'small_bert/bert_en_uncased_L-8_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-8_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-8_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-8_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-768_A-12/1',
    'small_bert/bert_en_uncased_L-10_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-10_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-10_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-10_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-10_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-10_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-10_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-10_H-768_A-12/1',
    'small_bert/bert_en_uncased_L-12_H-128_A-2':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-12_H-128_A-2/1',
    'small_bert/bert_en_uncased_L-12_H-256_A-4':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-12_H-256_A-4/1',
    'small_bert/bert_en_uncased_L-12_H-512_A-8':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-12_H-512_A-8/1',
    'small_bert/bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-12_H-768_A-12/1',
    'albert_en_base':
        'https://tfhub.dev/tensorflow/albert_en_base/2',
    'electra_small':
        'https://tfhub.dev/google/electra_small/2',
    'electra_base':
        'https://tfhub.dev/google/electra_base/2',
    'experts_pubmed':
        'https://tfhub.dev/google/experts/bert/pubmed/2',
    'experts_wiki_books':
        'https://tfhub.dev/google/experts/bert/wiki_books/2',
    'talking-heads_base':
        'https://tfhub.dev/tensorflow/talkheads_ggelu_bert_en_base/1',
}

map_model_to_preprocess = {
    'bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'bert_en_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_cased_preprocess/2',
    'small_bert/bert_en_uncased_L-2_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-2_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-2_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-2_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-4_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-4_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-4_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-4_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-6_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-6_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-6_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-6_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-8_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-8_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-8_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-8_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-10_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-10_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-10_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-10_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-12_H-128_A-2':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-12_H-256_A-4':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-12_H-512_A-8':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'small_bert/bert_en_uncased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'bert_multi_cased_L-12_H-768_A-12':
        'https://tfhub.dev/tensorflow/bert_multi_cased_preprocess/2',
    'albert_en_base':
        'https://tfhub.dev/tensorflow/albert_en_preprocess/2',
    'electra_small':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'electra_base':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'experts_pubmed':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'experts_wiki_books':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
    'talking-heads_base':
        'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2',
}

tfhub_handle_encoder = map_name_to_handle[bert_model_name]
tfhub_handle_preprocess = map_model_to_preprocess[bert_model_name]

print(f'BERT model selected           : {tfhub_handle_encoder}')
print(f'Preprocess model auto-selected: {tfhub_handle_preprocess}')

BERT model selected           : https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-512_A-8/1
Preprocess model auto-selected: https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2


In [4]:
bert_preprocess_model = hub.KerasLayer(tfhub_handle_preprocess)


2023-10-04 10:26:06.504591: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-04 10:26:06.571674: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-04 10:26:06.573889: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [5]:
features= ["chinese food shops near me", "how to download a song from spotify", "buy best cat ear headphones", "saloons near me"]


import pandas as pd

features= pd.Series(features).values
features

array(['chinese food shops near me',
       'how to download a song from spotify',
       'buy best cat ear headphones', 'saloons near me'], dtype=object)

In [6]:
features_preprocessed= bert_preprocess_model(features)
features_preprocessed

{'input_type_ids': <tf.Tensor: shape=(4, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [7]:
my_reloaded_model = tf.keras.models.load_model(
       ("models/intent_classifier.h5"),
       custom_objects={'KerasLayer':hub.KerasLayer}
)

In [8]:
features

array(['chinese food shops near me',
       'how to download a song from spotify',
       'buy best cat ear headphones', 'saloons near me'], dtype=object)

In [9]:

prediction= my_reloaded_model.predict({
                                       "text": features
                                       
                                       })

1/1 [==============================] - 1s 557ms/step


2023-10-04 10:26:15.036423: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [10]:
prediction

array([[0.23743875, 0.09801065, 0.40351167, 0.0751248 , 0.18591411],
       [0.23768729, 0.3171847 , 0.07827991, 0.01379045, 0.35305768],
       [0.32586142, 0.21016091, 0.09709751, 0.09010372, 0.27677643],
       [0.27478555, 0.20986514, 0.15953411, 0.07572418, 0.28009105]],
      dtype=float32)

In [11]:
tf.constant(pd.Series(features[0]).values)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'chinese food shops near me'], dtype=object)>

In [12]:
intent= {
    0: "commercial", 
    1: "informational", 
    2: "local", 
    3: "navigational",
    4: "transactional"
}
import numpy as np

In [13]:
for i in features:
    print(f"feature: {i}")
    raw_result= my_reloaded_model(tf.constant(pd.Series(i).values))
    raw_result_softmax= tf.keras.activations.softmax(raw_result)
    max_index= np.argmax(raw_result_softmax[0])
    
    print(f"raw result: {raw_result}")
    print(f"softmax: {raw_result_softmax}")
    
    print(f"maximum index: {max_index}, intent: {intent[max_index]}")
    print()

feature: chinese food shops near me
raw result: [[0.23744346 0.09794604 0.40338737 0.07516549 0.18605761]]
softmax: [[0.20616774 0.17932373 0.24338244 0.17528482 0.19584124]]
maximum index: 2, intent: local

feature: how to download a song from spotify
raw result: [[0.23761839 0.31721643 0.07824647 0.01378405 0.35313472]]
softmax: [[0.20587015 0.22292683 0.17554116 0.16458237 0.23107952]]
maximum index: 4, intent: transactional

feature: buy best cat ear headphones
raw result: [[0.3258132  0.21019603 0.09703994 0.09007353 0.27687728]]
softmax: [[0.22580737 0.20115286 0.17963175 0.17838472 0.21502328]]
maximum index: 0, intent: commercial

feature: saloons near me
raw result: [[0.2749512  0.20967849 0.15961565 0.0757378  0.2800168 ]]
softmax: [[0.21494594 0.20136392 0.19153126 0.17612134 0.21603754]]
maximum index: 4, intent: transactional



In [14]:
import pandas as pd
dataset= pd.read_csv("data/keyword_intent.csv")

In [15]:
for i in dataset.values[:5]:
    print(i)

['citalopram vs prozac' 'Commercial']
['who is the oldest football player' 'Informational']
['t mobile town east' 'Navigational']
['starbucks' 'Navigational']
['tech crunch' 'Navigational']


In [16]:
true_count=0
false_count=0
import time

for i in dataset.values:
    print(f"feature: {i[0]}")
    raw_result= my_reloaded_model(tf.constant(pd.Series(i[0]).values))
    raw_result_softmax= tf.keras.activations.softmax(raw_result)
    max_index= np.argmax(raw_result[0])
    
    # print(f"raw result: {raw_result}")
    # print(f"softmax: {raw_result_softmax}")
    
    # print(f"maximum index: {max_index}, intent: {intent[max_index]}")
    
    if intent[max_index].lower()==i[1].lower():
        true_count+=1
    else:
        false_count+=1
        print(f"predicted intent: {intent[max_index]}")
        print(f"true intent: {i[1]}")
        # time.sleep(5)
    
    print()

feature: citalopram vs prozac

feature: who is the oldest football player

feature: t mobile town east
predicted intent: informational
true intent: Navigational

feature: starbucks
predicted intent: commercial
true intent: Navigational

feature: tech crunch
predicted intent: informational
true intent: Navigational

feature: screen protector

feature: chinese food delivery near me
predicted intent: commercial
true intent: Local

feature: elevenlabs
predicted intent: informational
true intent: Navigational

feature: llama

feature: tire patch kit
predicted intent: informational
true intent: Transactional

feature: cat shelves
predicted intent: informational
true intent: Transactional

feature: bx headphones

feature: bx headphones

feature: duffel bags
predicted intent: transactional
true intent: Commercial

feature: best cat ear headphones
predicted intent: transactional
true intent: Commercial

feature: MS Dhoni

feature: best food
predicted intent: informational
true intent: Commercia

predicted intent: informational
true intent: Navigational

feature: spotify
predicted intent: informational
true intent: Navigational

feature: ibm
predicted intent: commercial
true intent: Navigational

feature: pudding recepie
predicted intent: commercial
true intent: Informational

feature: pudding recepie
predicted intent: commercial
true intent: Informational

feature: pudding recepie
predicted intent: commercial
true intent: Informational

feature: pudding recepie
predicted intent: commercial
true intent: Informational

feature: pudding recepie
predicted intent: commercial
true intent: Informational

feature: band manager download
predicted intent: commercial
true intent: Informational

feature: band manager download
predicted intent: commercial
true intent: Informational

feature: Fast and The Furious

feature: Fast and The Furious

feature: Fast and The Furious

feature: music industry
predicted intent: commercial
true intent: Informational

feature: Fast and The Furious

featu

In [17]:
print(f"true_count= {true_count}")
print(f"false_count= {false_count}")

true_count= 291
false_count= 780
